# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates every week
    schedule:
      interval: "weekly"
    # Limit to security updates
    open-pull-requests-limit: 10
    # Group all minor and patch updates together
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch" 