name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Check Node.js version
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: npm ci
      env:
        CI: true
    
    - name: Build project
      run: npm run build
      env:
        CI: true
    
    - name: Test build output
      run: |
        if [ -d ".next" ]; then
          echo "✅ Build successful - .next directory created"
          ls -la .next/
          echo "Build size:"
          du -sh .next/
        else
          echo "❌ Build failed - .next directory not found"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi 